version: "2"

services:
  server:
    image: server
    ports:
      - "9090:9090"
    container_name: server-0
  controle-de-estoque:
    image: controle-de-estoque
    ports:
      - "9000:9000"
    depends_on:
      - server
    container_name: controle-de-estoque-0
  controle-de-pedidos:
    image: controle-de-pedidos
    ports:
      - "9000:9000"
    depends_on:
      - server
      - controle-de-estoque
    container_name: controle-de-pedidos-0
  processador-de-pagamentos:
    image: processador-de-pagamentos
    ports:
      - "9000:9000"
    depends_on:
      - server
    container_name: processador-de-pagamentos-0
  notificador:
    image: notificador
    ports:
      - "9000:9000"
    depends_on:
      - server
    container_name: notificador-0