server:
  port: '9005'
spring:
  application:
    name: notificador
eureka:
  client:
    service-url:
      defaultZone: 'http://server:9090/eureka'
  instance:
    instance-id: '${spring.application.name}:${random.int}'