server:
  port: 9090
spring:
  application:
    name: server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
management:
  endpoints:
    web:
      exposure:
        include: "*"