server:
  port: '9003'
spring:
  application:
    name: controle-de-pedidos
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:9090/eureka'
  instance:
    instance-id: '${spring.application.name}:${random.int}'