server:
  port: '9006'
spring:
  application:
    name: processador-de-pagamentos
eureka:
  client:
    service-url:
      defaultZone: 'http://server:9090/eureka'
  instance:
    instance-id: '${spring.application.name}:${random.int}'